# this config was migrated from renv.lock on 2026-06-26
[project]
name = "dev-gca-mr"
r_version = "4.6"

repositories = [
    { alias = "CRAN", url = "https://cloud.r-project.org/"},
    { alias = "BioCsoft", url = "https://bioconductor.org/packages/3.23/bioc"},
    { alias = "BioCann", url = "https://bioconductor.org/packages/3.23/data/annotation"},
    { alias = "BioCexp", url = "https://bioconductor.org/packages/3.23/data/experiment"},
    { alias = "BioCworkflows", url = "https://bioconductor.org/packages/3.23/workflows"},
    { alias = "BioCbooks", url = "https://bioconductor.org/packages/3.23/books"}
]

dependencies = [
    { name = "BH", repository = "CRAN" },
    { name = "BiocManager", repository = "CRAN" },
    { name = "R.methodsS3", repository = "CRAN" },
    { name = "R6", repository = "CRAN" },
    { name = "RCurl", repository = "CRAN" },
    { name = "XML", repository = "CRAN" },
    { name = "abind", repository = "CRAN" },
    { name = "askpass", repository = "CRAN" },
    { name = "bitops", repository = "CRAN" },
    { name = "cpp11", repository = "CRAN" },
    { name = "crayon", repository = "CRAN" },
    { name = "curl", repository = "CRAN" },
    { name = "data.table", repository = "CRAN" },
    { name = "formatR", repository = "CRAN" },
    { name = "futile.logger", repository = "CRAN" },
    { name = "futile.options", repository = "CRAN" },
    { name = "generics", repository = "CRAN" },
    { name = "httr", repository = "CRAN" },
    { name = "jsonlite", repository = "CRAN" },
    { name = "lambda.r", repository = "CRAN" },
    { name = "matrixStats", repository = "CRAN" },
    { name = "mime", repository = "CRAN" },
    { name = "openssl", repository = "CRAN" },
    { name = "renv", repository = "CRAN" },
    { name = "restfulr", repository = "CRAN" },
    { name = "rjson", repository = "CRAN" },
    { name = "snow", repository = "CRAN" },
    { name = "sys", repository = "CRAN" },
    { name = "yaml", repository = "CRAN" },
    "rtracklayer",
    "R.utils",
    "optparse",
]
